# Generated by Django 4.1.3 on 2022-11-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=211)),
                ('image', models.ImageField(upload_to='rooms/')),
                ('day', models.IntegerField(choices=[(0, 'day'), (1, 'night')], default=0)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=211)),
                ('title', models.CharField(max_length=211)),
                ('image', models.ImageField(upload_to='service/')),
                ('content', models.TextField()),
            ],
        ),
    ]
