# Generated by Django 4.1.3 on 2022-11-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marian', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='e_d',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out',
            new_name='s_d',
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=211, null=True),
        ),
    ]
