# Generated by Django 4.1.3 on 2022-11-15 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marian', '0002_rename_check_in_booking_e_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marian.room'),
        ),
    ]
