# Generated by Django 4.1.3 on 2022-11-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('phone', models.CharField(max_length=221)),
                ('email', models.EmailField(max_length=221)),
                ('message', models.TextField()),
            ],
        ),
    ]
